# https://circleci.com/docs/2.0/testing-ios/
version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.1.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
        # Pre-start the iOS simulator before building your application to make
        # sure that the simulator is booted in time. Doing so generally reduces
        # the number of simulator timeouts observed in builds.
        # 
        # To pre-start the simulator, add the following to your config.yml
        # file, assuming that you are running your tests on an iPhone 7
        # simulator with iOS 10.2:
      - run:
          name: pre-start simulator
          command: xcrun instruments -w "iPhone 5s (12.1) [" || true
      - run:
          name: Install required Ruby gems
          command: bundle install
      # In addition to the basic setup steps, it is best practice to
      # include downloading CocoaPods specs from the CircleCI mirror (up to
      # 70% faster) and linting the Swift code together with the
      # build-and-test job:
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install CocoaPods
          command: bundle exec fastlane run cocoapods
      - run:
          name: Create output directory
          command: mkdir -p output/scan
      - run:
          name: Build and run tests
          command: bundle exec fastlane scan --output_directory output/scan
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test

